 insert into equipement(idEquipement,NOMEQUIPEMENT,TYPEEQUIPEMENT,QUANTITEEQUIPEMENT,ETATEQUIPEMENT,DATEFABRICATION) VALUES('1','pistolet','type1','23','1','23/05/2000');
 insert into equipement(idEquipement,NOMEQUIPEMENT,TYPEEQUIPEMENT,QUANTITEEQUIPEMENT,ETATEQUIPEMENT,DATEFABRICATION) VALUES('2','chocElectrique','type1','70','1','23/05/2017');
